'use client';
import Link from 'next/link';
import { useMemo, useState } from 'react';
import { useStore } from '@/context/store';
import { Product, Category, Slide, ShippingOption } from '@/lib/types';

const formatPrice = (fcfa: number, currency: string) => currency === 'USD' ? `${(fcfa / 600).toFixed(2)} USD` : `${fcfa.toLocaleString('fr-FR')} FCFA`;

export const CurrencySwitcher = () => { const { currency, setCurrency } = useStore(); return <select className='rounded-full border px-3 py-2 text-sm' value={currency} onChange={(e)=>setCurrency(e.target.value as 'FCFA' | 'USD')}><option>FCFA</option><option>USD</option></select>; };
export const LanguageSwitcher = () => { const { locale, setLocale } = useStore(); return <select className='rounded-full border px-3 py-2 text-sm' value={locale} onChange={(e)=>setLocale(e.target.value as 'fr' | 'en' | 'zh')}><option value='fr'>FR</option><option value='en'>EN</option><option value='zh'>中文</option></select>; };

export const HeroSlider = ({ slides }: { slides: Slide[] }) => <div className='overflow-hidden rounded-3xl bg-gradient-to-br from-slate-950 via-slate-900 to-emerald-950 text-white shadow-2xl'>{slides.slice(0,1).map(s => <div key={s.id} className='grid items-center gap-8 p-8 md:grid-cols-2 md:p-12'><div><p className='mb-3 inline-block rounded-full border border-white/20 px-3 py-1 text-xs'>Marketplace africaine premium</p><h1 className='text-3xl font-bold md:text-5xl'>{s.title}</h1><p className='mt-4 max-w-xl text-slate-200'>{s.subtitle}</p><div className='mt-6 flex flex-wrap gap-3'><Link href='/catalogue' className='rounded-full bg-amber-400 px-5 py-3 font-semibold text-slate-900'>Explorer la marketplace</Link><Link href='/vendor-apply' className='rounded-full border border-white/40 px-5 py-3'>Vendre sur Diamarket</Link></div></div><img src={s.imageUrl} loading='eager' className='h-72 w-full rounded-2xl object-cover md:h-96' /></div>)}</div>;

export const CategoryCard = ({ category }: { category: Category }) => <div className='group rounded-2xl bg-white p-3 shadow-sm ring-1 ring-slate-100 transition hover:-translate-y-1 hover:shadow-lg'><img src={category.imageUrl} loading='lazy' className='h-32 w-full rounded-xl object-cover'/><h3 className='mt-3 font-semibold'>{category.name}</h3><p className='text-sm text-slate-500'>{category.productCount} produits</p></div>;

export const ProductCard = ({ product, onAdd }: { product: Product; onAdd: (p: Product)=>void; }) => { const { currency } = useStore(); return <div className='rounded-2xl bg-white p-3 shadow-sm ring-1 ring-slate-100'><div className='relative'><img src={product.images[0]} loading='lazy' className='h-44 w-full rounded-xl object-cover'/>{product.isPromo && <span className='absolute left-2 top-2 rounded-full bg-rose-500 px-2 py-1 text-xs text-white'>Promo</span>}</div><h3 className='mt-3 line-clamp-1 font-semibold'>{product.name}</h3><p className='text-sm text-slate-600'>{formatPrice(product.priceFcfa, currency)}</p><div className='mt-3 flex gap-2'><Link href={`/product/${product.id}`} className='rounded-full border px-3 py-1.5 text-sm'>Voir</Link><button onClick={()=>onAdd(product)} className='rounded-full bg-[#556B2F] px-3 py-1.5 text-sm text-white'>Ajouter</button></div></div>; };

export const CartDrawer = () => { const { cart, totalFcfa } = useStore(); const [open,setOpen]=useState(false); return <div className='relative'><button onClick={()=>setOpen(!open)} className='rounded-full bg-black px-3 py-2 text-sm text-white'>Panier ({cart.length})</button>{open && <div className='absolute right-0 top-12 z-20 w-80 rounded-2xl bg-white p-4 shadow-2xl ring-1 ring-slate-200'><p className='font-semibold'>Mini panier</p><div className='mt-2 max-h-56 space-y-2 overflow-auto'>{cart.length===0?<p className='text-sm text-slate-500'>Panier vide</p>:cart.map(item=><div key={item.product.id} className='flex items-center justify-between text-sm'><span className='line-clamp-1'>{item.product.name}</span><span>x{item.quantity}</span></div>)}</div><p className='mt-3 text-sm font-semibold'>Sous-total: {totalFcfa} FCFA</p><Link href='/cart' className='mt-3 inline-block w-full rounded-full bg-black px-4 py-2 text-center text-sm text-white'>Voir le panier</Link></div>}</div>; };

export const CheckoutSummary = ({ shipping = 0 }: { shipping?: number }) => { const { totalFcfa, currency } = useStore(); const total = totalFcfa + shipping; return <div className='sticky top-4 rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-100'><p>Sous-total: {formatPrice(totalFcfa, currency)}</p><p>Livraison: {formatPrice(shipping, currency)}</p><p className='mt-3 text-lg font-bold'>Total: {formatPrice(total, currency)}</p></div>; };
export const ShippingOptions = ({ options, selected, onSelect }: { options: ShippingOption[]; selected?: string; onSelect: (id: string)=>void; }) => <div className='space-y-2'>{options.map(o => <button key={o.id} onClick={()=>onSelect(o.id)} className={`w-full rounded-xl border p-3 text-left text-sm ${selected===o.id?'border-amber-400 bg-amber-50':'border-slate-200'}`}>{o.name} - {o.priceFcfa} FCFA ({o.etaDays})</button>)}</div>;
export const StatusBadge = ({ status }: { status: string }) => <span className='rounded-full bg-slate-100 px-2 py-1 text-xs'>{status}</span>;

export const SearchBar = ({ products }: { products: Product[] }) => {
  const [q, setQ] = useState('');
  const [history, setHistory] = useState<string[]>([]);
  const results = useMemo(() => products.filter(p => p.name.toLowerCase().includes(q.toLowerCase())).slice(0, 6), [products, q]);
  const save = (term: string) => term && setHistory(prev => [term, ...prev.filter(x=>x!==term)].slice(0,4));
  return <div className='rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-100'><input value={q} onChange={e=>setQ(e.target.value)} onBlur={()=>save(q)} className='w-full rounded-xl border p-3' placeholder='Rechercher un produit, une marque, une catégorie...' />{q && <div className='mt-2 space-y-1'>{results.map(r=><Link key={r.id} href={`/product/${r.id}`} className='block rounded-lg px-2 py-1 text-sm hover:bg-slate-50'>{r.name}</Link>)}</div>}{history.length>0 && <p className='mt-2 text-xs text-slate-500'>Historique: {history.join(' · ')}</p>}</div>;
};
