'use client';
import Link from 'next/link';
import { useMemo, useState } from 'react';
import { useStore } from '@/context/store';
import { Product, Category, Slide, ShippingOption } from '@/lib/types';

const formatPrice = (fcfa: number, currency: string) => currency === 'USD' ? `${(fcfa / 600).toFixed(2)} USD` : `${fcfa.toLocaleString('fr-FR')} FCFA`;

export const CurrencySwitcher = () => { const { currency, setCurrency } = useStore(); return <select aria-label='Devise' className='rounded-xl border px-2 text-sm' value={currency} onChange={(e)=>setCurrency(e.target.value as 'FCFA' | 'USD')}><option>FCFA</option><option>USD</option></select>; };
export const LanguageSwitcher = () => { const { locale, setLocale } = useStore(); return <select aria-label='Langue' className='rounded-xl border px-2 text-sm' value={locale} onChange={(e)=>setLocale(e.target.value as 'fr' | 'en' | 'zh')}><option value='fr'>FR</option><option value='en'>EN</option><option value='zh'>中文</option></select>; };

export const HeroSlider = ({ slides }: { slides: Slide[] }) => <div className='overflow-hidden rounded-3xl bg-gradient-to-br from-slate-950 via-slate-900 to-emerald-950 text-white shadow-xl'>{slides.slice(0,1).map(s => <div key={s.id} className='grid items-center gap-8 p-6 md:grid-cols-2 md:p-12'><div><p className='mb-3 inline-block rounded-full border border-white/20 px-3 py-1 text-xs'>Marketplace africaine de confiance</p><h1 className='text-3xl font-bold tracking-tight md:text-5xl'>{s.title}</h1><p className='mt-4 max-w-xl text-slate-200'>{s.subtitle}</p><div className='mt-6 flex flex-col gap-3 sm:flex-row'><Link href='/catalogue' className='btn-primary bg-amber-400 text-slate-950 hover:bg-amber-300'>Explorer les produits</Link><Link href='/vendor-apply' className='btn-secondary border-white/40 bg-transparent text-white hover:bg-white/10'>Vendre sur Diamarket</Link></div></div><img src={s.imageUrl} alt={s.title} loading='eager' className='h-64 w-full rounded-2xl object-cover md:h-96' /></div>)}</div>;

export const CategoryCard = ({ category }: { category: Category }) => <div className='surface group p-3 transition hover:-translate-y-1 hover:shadow-lg'><img src={category.imageUrl || '/placeholder.svg'} alt='' loading='lazy' className='h-28 w-full rounded-xl object-cover sm:h-32'/><h3 className='mt-3 font-semibold'>{category.name}</h3><p className='text-sm text-slate-500'>{category.productCount} produits</p></div>;

export const ProductCard = ({ product, onAdd }: { product: Product; onAdd: (p: Product)=>void; }) => { const { currency } = useStore(); const unavailable=product.stock<=0; return <article className='surface flex min-w-0 flex-col p-3'><div className='relative'><img src={product.images[0] || '/placeholder.svg'} alt={product.name} loading='lazy' className='aspect-square w-full rounded-xl object-cover'/><div className='absolute left-2 top-2 flex flex-wrap gap-1'>{product.isPromo && <span className='rounded-full bg-rose-600 px-2 py-1 text-xs font-medium text-white'>Promotion</span>}{unavailable && <span className='rounded-full bg-slate-900 px-2 py-1 text-xs text-white'>Indisponible</span>}</div></div><h3 className='mt-3 line-clamp-2 min-h-12 font-semibold'>{product.name}</h3><p className='text-sm font-bold text-emerald-900'>{formatPrice(product.priceFcfa, currency)}</p><p className='mt-1 truncate text-xs text-slate-500'>{product.vendor?.name ? `Vendu par ${product.vendor.name}` : 'Vendeur Diamarket'}</p><div className='mt-auto grid grid-cols-2 gap-2 pt-3'><Link href={`/product/${product.slug}`} className='btn-secondary px-2'>Voir</Link><button disabled={unavailable} onClick={()=>onAdd(product)} className='btn-primary px-2'>Ajouter</button></div></article>; };

export const LoadingGrid = () => <div aria-label='Chargement des produits' role='status' className='grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-4'>{Array.from({length:8},(_,i)=><div key={i} className='surface animate-pulse p-3'><div className='aspect-square rounded-xl bg-slate-200'/><div className='mt-3 h-4 rounded bg-slate-200'/><div className='mt-2 h-4 w-2/3 rounded bg-slate-200'/></div>)}</div>;
export const EmptyState = ({ title, description, action }: {title:string; description:string; action?:React.ReactNode}) => <div className='surface border-dashed p-8 text-center'><div aria-hidden className='text-3xl'>◇</div><h2 className='mt-3 text-lg font-bold'>{title}</h2><p className='mx-auto mt-1 max-w-md text-sm text-slate-600'>{description}</p>{action&&<div className='mt-5'>{action}</div>}</div>;
export const ErrorState = ({ message, onRetry }: {message:string; onRetry?:()=>void}) => <div role='alert' className='rounded-2xl border border-red-200 bg-red-50 p-5 text-red-900'><p className='font-semibold'>Une erreur est survenue</p><p className='mt-1 text-sm'>{message}</p>{onRetry&&<button className='btn-secondary mt-4' onClick={onRetry}>Réessayer</button>}</div>;

export const CartDrawer = () => { const { cart, totalFcfa } = useStore(); const [open,setOpen]=useState(false); return <div className='relative'><button onClick={()=>setOpen(!open)} className='rounded-full bg-black px-3 py-2 text-sm text-white'>Panier ({cart.length})</button>{open && <div className='absolute right-0 top-12 z-20 w-80 rounded-2xl bg-white p-4 shadow-2xl ring-1 ring-slate-200'><p className='font-semibold'>Mini panier</p><div className='mt-2 max-h-56 space-y-2 overflow-auto'>{cart.length===0?<p className='text-sm text-slate-500'>Panier vide</p>:cart.map(item=><div key={item.product.id} className='flex items-center justify-between text-sm'><span className='line-clamp-1'>{item.product.name}</span><span>x{item.quantity}</span></div>)}</div><p className='mt-3 text-sm font-semibold'>Sous-total: {totalFcfa} FCFA</p><Link href='/cart' className='mt-3 inline-block w-full rounded-full bg-black px-4 py-2 text-center text-sm text-white'>Voir le panier</Link></div>}</div>; };

export const CheckoutSummary = ({ shipping = 0 }: { shipping?: number }) => { const { totalFcfa, currency } = useStore(); const total = totalFcfa + shipping; return <div className='sticky top-4 rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-100'><p>Sous-total: {formatPrice(totalFcfa, currency)}</p><p>Livraison: {formatPrice(shipping, currency)}</p><p className='mt-3 text-lg font-bold'>Total: {formatPrice(total, currency)}</p></div>; };
export const ShippingOptions = ({ options, selected, onSelect }: { options: ShippingOption[]; selected?: string; onSelect: (id: string)=>void; }) => <div className='space-y-2'>{options.map(o => <button key={o.id} onClick={()=>onSelect(o.id)} className={`w-full rounded-xl border p-3 text-left text-sm ${selected===o.id?'border-amber-400 bg-amber-50':'border-slate-200'}`}>{o.name} - {o.priceFcfa} FCFA ({o.etaDays})</button>)}</div>;
export const StatusBadge = ({ status }: { status: string }) => <span className='rounded-full bg-slate-100 px-2 py-1 text-xs'>{status}</span>;

export const SearchBar = ({ products }: { products: Product[] }) => {
  const [q, setQ] = useState('');
  const [history, setHistory] = useState<string[]>([]);
  const results = useMemo(() => products.filter(p => p.name.toLowerCase().includes(q.toLowerCase())).slice(0, 6), [products, q]);
  const save = (term: string) => term && setHistory(prev => [term, ...prev.filter(x=>x!==term)].slice(0,4));
  return <div className='rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-100'><input value={q} onChange={e=>setQ(e.target.value)} onBlur={()=>save(q)} className='w-full rounded-xl border p-3' placeholder='Rechercher un produit, une marque, une catégorie...' />{q && <div className='mt-2 space-y-1'>{results.map(r=><Link key={r.id} href={`/product/${r.id}`} className='block rounded-lg px-2 py-1 text-sm hover:bg-slate-50'>{r.name}</Link>)}</div>}{history.length>0 && <p className='mt-2 text-xs text-slate-500'>Historique: {history.join(' · ')}</p>}</div>;
};
